### ISSUE TITLE
Deploying smart contract

### ISSUE THREAD

**Issue by TheCrypticCamel** [juliancwirko/nft-art-maker#4]
Hi Julian,

So I've followed the entirety of the walkthrough many times and there's one thing that I'm stuck on and just can't figure out, and that's how to deploy the nft-art-maker as a smart contract.. It works on my system to generate the svgs but how do I deploy the smart contract to then have the smart contract address to put into the config file on the elven-mint script? A video showing this part or the whole process from start to finish would be really helpful at some point if you ever have the time! :)

Thanks!

**Comment by juliancwirko** [comment]
Hi, this is not in the scope of this library, I will publish an example of such a smart contract soon (in separate repo), but the best reference, for now, would be: https://github.com/ElrondNetwork/elrond-wasm-rs/tree/master/contracts/examples/nft-minter. 

My custom smart contract will probably be very similar. Its first version already lives on the devnet, but I don't want to publish it yet because it needs more work.

I also plan to record a longer video that will show the entire path from deploying the smart contract, adding special roles, issuing esdt, and using nft-art-maker and [elven-mint](https://github.com/juliancwirko/elven-tools). But it has to wait for the smart contract.

Anyway, this library is only for creating the images, and in version 3, it also allows to pack the files and metadata with [ipfs-car](https://github.com/web3-storage/ipfs-car).
